### ISSUE TITLE
Unexpected end of expression: Ui.turnOn

### ISSUE THREAD

**Issue by raywu** [mcasimir/mobile-angular-ui#198]
I have been trying to access SharedState (core) in my controller, but am not having much luck.

In the context of setting up Modal: at first I tried to access Ui like the Doc suggests by using ng-click="Ui.turnOn('myVar')"

This throws an error: 
<pre>
Error: [$parse:ueoe] Unexpected end of expression: Ui.turnOn('modal2'
http://errors.angularjs.org/1.3.8/$parse/ueoe?p0=Ui.turnOn('modal2'
    at http://0.0.0.0:9000/bower_components/angular/angular.js:63:12
    at Parser.consume (http://0.0.0.0:9000/bower_components/angular/angular.js:12035:13)
    at Parser.functionCall (http://0.0.0.0:9000/bower_components/angular/angular.js:12310:10)
    at Parser.primary (http://0.0.0.0:9000/bower_components/angular/angular.js:11982:24)
    at Parser.unary (http://0.0.0.0:9000/bower_components/angular/angular.js:12258:19)
    at Parser.multiplicative (http://0.0.0.0:9000/bower_components/angular/angular.js:12241:21)
    at Parser.additive (http://0.0.0.0:9000/bower_components/angular/angular.js:12232:21)
    at Parser.relational (http://0.0.0.0:9000/bower_components/angular/angular.js:12223:21)
    at Parser.equality (http://0.0.0.0:9000/bower_components/angular/angular.js:12214:21)
    at Parser.logicalAND (http://0.0.0.0:9000/bower_components/angular/angular.js:12205:21) <button ng-click="Ui.turnOn('modal2'">
</pre>

I tried to pass in the SharedState service, but this is undefined.

<pre>
angular.module('MagicBus')
  .controller('Ctrl', ['$rootScope', '$scope', '$state', 'SharedState',
  function UpcomingTripsCtrl($rootScope, $scope, $state, SharedState) {
    …code…
}
</pre>

This is how the Mobile Angular UI is loaded, my understanding is that core should be part of the dependencies already.

<pre>
var app = angular.module('MagicBus', [
  'mobile-angular-ui',
  'mobile-angular-ui.plugins.ui-router',
  'ui.router',
]);

**Comment by renatomefidf** [comment]
Have you tried:

```html
angular.module('MagicBus')
  .controller('Ctrl', ['$rootScope', '$scope', '$state', 'SharedState',
  function UpcomingTripsCtrl($rootScope, $scope, $state, SharedState) {
    $scope.Ui.turnOn("myVar");
}
```

Please check if your ui-state='myVar' is corret, the error you sent was 'modal12' and your code shows 'myVar'
