### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by mac-s-g** [mcasimir/mobile-angular-ui#226]
Running `sudo gulp build` on ubuntu 14.04 i get the following output.  I'm having a hard time debugging bc the error message is empty.  any insight is helpful.

[05:51:21] Using gulpfile ~/git/app/gulpfile.js
[05:51:21] Starting 'build'...
[05:51:21] Starting 'clean'...
[05:51:21] Finished 'clean' after 27 ms
[05:51:21] Starting 'html'...
[05:51:21] Finished 'html' after 2.59 ms
[05:51:21] Starting 'fonts'...
[05:51:21] Starting 'images'...
[05:51:21] Starting 'less'...
[05:51:21] Finished 'less' after 6.17 ms
[05:51:21] Starting 'js'...
[05:51:21] Finished 'js' after 19 ms
[05:51:21] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
[05:51:21] Finished 'images' after 47 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new Parser (/home/myuser/git/app/node_modules/gulp-less/node_modules/less/lib/less/parser.js:333:27)
    at Object.less.render (/home/myuser/git/app/node_modules/gulp-less/node_modules/less/lib/less/index.js:18:22)
    at Transform._transform (/home/myuser/git/app/node_modules/gulp-less/index.js:38:10)
    at Transform._read (/home/myuser/git/app/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/myuser/git/app/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/myuser/git/app/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/myuser/git/app/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/myuser/git/app/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/myuser/git/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/myuser/git/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

let me know if this is something that should be moved over to gulpjs/gulp.  i was running through the setup at http://mobileangularui.com/ and this is the first issue i came across.  not sure what's causing the error.

**Comment by mikrofusion** [comment]
:+1: also hitting the error on a on OS X Yosemite‎.

**Comment by GiankOtarola** [comment]
i have the same error, any solution?

**Comment by ava-taylorb** [comment]
Same exact issue.  Dont know if this is due to a user permissions issue or what.  Would love to see a solution because i am looking forward to using this package

**Comment by lukasT** [comment]
same here: Ubuntu 14.04 LTS, node v0.12.0, gulp v3.8.11

**Comment by lukasT** [comment]
update: I was able to get around by issuing:

npm uninstall gulp-less

and then issuing:

npm install gulp-less

now I got gulp-less at version 2.5.1 and it is working.

Seemed to be some version-problems. Just fyi: After fixing this, i ran into an error saying that there is no spinning.less .... if you get the same, find /bower_components/mobile-angular-ui/src/less/mobile-angular-ui.less and remove the line with @import "font-awesome/less/spinning.less"

**Comment by Schoonmoeder** [comment]
This problem is easier solved i got the idea from anothe issue (https://github.com/mcasimir/generator-mobileangularui/issues/8) 

just go to the folder of the app and run these commands.
bower uninstall font-awesome
and
bower install font-awesome#4.2.0

choise option 1 when it ask if you want to install 4.3.x or 4.2.0 of awesome

**Comment by namelivia** [comment]
Same here, fixed using Schoonmoeder's solution.

**Comment by Zandy** [comment]
Same here, fixed using lukasT's solution. thanks!

**Comment by GiankOtarola** [comment]
Perfects solutions. Thanks lukasT and Schoonmoeder !

**Comment by wayou** [comment]
same problem here. solved using @Schoonmoeder's way.

**Comment by juanjoc333** [comment]
Same problem here and solved using @Schoonmoeder's way.

**Comment by Bup3** [comment]
Same problem here and solved using @lukasT's and @Schoonmoeder's way.

**Comment by RemcovandenBerg** [comment]
@mcasimir The package need ot be updated on npm. Can you take care of this?

**Comment by mcasimir** [comment]
sure

**Comment by mcasimir** [comment]
`+ generator-mobileangularui@1.2.1`

**Comment by RemcovandenBerg** [comment]
fix confirmed, there shouldn't be a problem anymore when building from the generator.

**Comment by andrewmichaelsmith** [comment]
Is there any other way this could be occurring? I am fairly sure I am at 4.2 on font awesome (./bower_components/font-awesome/less/font-awesome.less lists 4.2.0) but I'm still getting the exact stack trace described above.

**Comment by mcasimir** [comment]
@andrewmichaelsmith update to 3+

**Comment by andrewmichaelsmith** [comment]
@mcasimir yes, I mistakenly put 2.5.1, have correct to 3.0.3. Thanks!
