### ISSUE TITLE
Installing AngularMobile [Error]

### ISSUE THREAD

**Issue by deadmann** [mcasimir/mobile-angular-ui#330]
i follow this toturial...
and i run this command:
npm install -g bower yo gulp generator-mobileangularui

i faced many errors...

https://github.com/npm/npm/issues/10620

**Comment by sam2x** [comment]
It looks like it's not a mobileangularui issue. npm config set registry http://registry.npmjs.org/

    24796 verbose stack Error: read ECONNRESET
    24796 verbose stack     at exports._errnoException (util.js:856:11)
    24796 verbose stack     at TLSWrap.onread (net.js:544:26)
    24797 verbose cwd F:\AngularMobile
    24798 error Windows_NT 6.3.9600


http://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset
The accepted solution : 

     npm config set registry http://registry.npmjs.org/

This issue should be closed

**Comment by deadmann** [comment]
Thank you for your information
